packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

overrides:
  multer: ^2.3.0

catalog:
  '@nestjs/common': ^11.1.6
  '@nestjs/core': ^11.1.6
  '@nestjs/platform-express': ^11.1.6
  '@nestjs/testing': ^11.1.6
  '@types/node': ^24.5.2
  'reflect-metadata': ^0.2.2
  'rxjs': ^7.8.2
  'typescript': ^5.9.2
